### ISSUE TITLE
Complete AffirmationCard function

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#3]
- Complete AffirmationCard function to use affirmation paramater. And pass its properties into correct places inside the Image composable's painter and contentDescription. 
- Also pass affirmation's appropriate property into Text composable.

**Comment by CommonHouseCat** [comment]
Hello @Abinash6000, I would like to work on this issue.

**Comment by Abinash6000** [comment]
Thanks for your contribution @CommonHouseCat !!!
