### ISSUE TITLE
Add 10 affirmation strings

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#5]
- Add 10 more affirmation strings to `strings.xml` file.
- name them affirmation3, affirmation4 and so on.

**Comment by sumedhakoranga** [comment]
Hi, I have submitted a [pull request](https://github.com/Abinash6000/Affirmations-App-Jetpack-Compose/pull/11) Could you please assign the issue to me and review the PR? Thanks!

**Comment by Abinash6000** [comment]
Please go ahead and work on this issue! Thanks!!

**Comment by sumedhakoranga** [comment]
Hi, I have submitted a [PR]( https://github.com/Abinash6000/Affirmations-App-Jetpack-Compose/pull/11), review the PR.

**Comment by Abinash6000** [comment]
Maybe you've deleted the repository from which you created the PR. So, the PR is not visible to me. Can you reopen the PR?

**Comment by sumedhakoranga** [comment]
Done, [check](https://github.com/Abinash6000/Affirmations-App-Jetpack-Compose/pull/12)

**Comment by Abinash6000** [comment]
Thank you for your contribution!!!
