### ISSUE TITLE
Remove unused imports from MainActivity.kt file

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#6]
- Remove unused imports from `MainActivity.kt` file.

**Comment by AshiqYadav** [comment]
please asign me this issue under `hacktoberfest`

**Comment by AshiqYadav** [comment]
please correct the spelling of `hacktoberfest` label . It has one `k` missing.

![image](https://github.com/user-attachments/assets/69cc07a7-a86a-4cc1-b24d-891905dd3164)
