### ISSUE TITLE
Add affirmations to Datasource.kt

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#7]
Add 10 affirmations to `Datasource.kt` file.
The is to be done after adding 10 strings to `strings.xml` file.

**Comment by TERRA2k5** [comment]
@Abinash6000 can i work on this issue ?

**Comment by Abinash6000** [comment]
Yes go ahead !!!

**Comment by TERRA2k5** [comment]
As i can see there are already 12 affirmations in String.xml , Do you want me to add 10 more ? also should they be from a famous author ?

**Comment by TERRA2k5** [comment]
As i can see there are already 12 affirmations in String.xml , Do you want me to add 10 more ? also should they be from a famous author ?

**Comment by Abinash6000** [comment]
No, just add the strings from `strings.xml` to `Datasource.kt`'s list where we're returning it. We don't need to update the `strings.xml`.

**Comment by TERRA2k5** [comment]
There are 12 strings but 10 images, what should i do for remaining images ?

**Comment by Abinash6000** [comment]
Remove 2 strings from `strings.xml`.

**Comment by TERRA2k5** [comment]
for removing 2 strings , can i remove affirmation3 since i could not find its author ?
