### ISSUE TITLE
Run and test the app if it works correctly.

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#8]
- Open developer mode in your mobile
- Enable usb debugging and test the app
- Check if it runs smoothly
- Paste some screenshots for this issue
- Add screenshots of the app to the `README.md` file

**Comment by Anayverma** [comment]
Hey @Abinash6000 , i would like to work on this issue.

**Comment by Abinash6000** [comment]
Please go ahead and work on this issue! Thanks!!

**Comment by bishwathakur** [comment]
]

> * Open developer mode in your mobile
> * Enable usb debugging and test the app
> * Check if it runs smoothly
> * Paste some screenshots for this issue
> * Add screenshots of the app to the `README.md` file

- I have enabled developer mode and USB debugging on my mobile device.
- I tested the app, and everything is running smoothly.
- I’ve added the requested screenshots to the README.md file.

Please review the changes and kindly accept the pull request.

**Comment by Abinash6000** [comment]
@Anayverma you can go ahead and work on this issue now. As all other issues are resolved now. So, you can test the app if it works fine.
