### ISSUE TITLE
Add the feature of author name in the Card

### ISSUE THREAD

**Issue by Abinash6000** [Abinash6000/Affirmations-App-Jetpack-Compose#9]
- Create a feature of author name in the Card for the affirmation.
- The card should show author of the affirmation at the bottom right corner.
- Add appropriate strings to `strings.xml` file for authors corresponding to affirmations.
- Update the model of the Affirmation data class.
- Update the dataSource to include this third parameter.
- Update the code in the `MainActivity.kt` to show author name.

**Comment by Anayverma** [comment]
Hey @Abinash6000 , i would like to work on this issue.

**Comment by Abinash6000** [comment]
Please suggest a solution how would you go about this... Thanks!!

**Comment by TERRA2k5** [comment]
@Abinash6000 is this issue open to work on ?

**Comment by Abinash6000** [comment]
Yes, it's open.

**Comment by TERRA2k5** [comment]
@Abinash6000 Can i work on this ?

**Comment by Abinash6000** [comment]
Yes, please go ahead.
